export type Property = {
  id: string;
  img: string;
  images?: string[];
  title: string;
  price: number;
  garag: number;
  bath: number;
  size: number;
  yearBuilt?: number;
  avatar: string;
  name: string;
  type: "sale" | "rent";
  description?: string;
  amenities?: string[];
  video?: string;
  status?: 'available' | 'pending' | 'sold';
  createdAt?: string;
  location?: string;
  bedrooms?: number;
  ownerId?: string;
  latitude?: number;
  longitude?: number;
};